version: "3.7"

services:
  backend:
    container_name: AshwinBlockchainV0.1_backend
    image: node:12-alpine
    working_dir: /usr/node/app
    volumes: 
      - ./backend/:/usr/node/app
    ports:
      - 3000:3000 
    command: node index.js
    
  database:
    container_name: AshwinBlockchainV0.1_database
    image: couchdb
    volumes: 
      - ~/.ashwinblockchaincouchdb/:/opt/couchdb/data
    ports:
      - 3984:5984